import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About",
    description: "Generated by create next app",
  };



export default function AbaoutPage(){
    return (
        <>
            <span className="text-7xl">Abaut Page</span>
        </>
    )
}